-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(250) NOT NULL,
    password character varying(25) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_employee
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_seeker
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    national_id character(11) NOT NULL,
    date_of_birth date,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.company_employer
(
    user_id integer NOT NULL,
    company_name character varying(250) NOT NULL,
    phone_number character varying(25) NOT NULL,
    web_address character varying(100) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.system_employee_roles
(
    id integer NOT NULL,
    employee_id integer NOT NULL,
    role character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seeker_verify
(
    id integer NOT NULL,
    job_seeker_id integer NOT NULL,
    mernis_verify boolean NOT NULL,
    email_verify boolean NOT NULL,
    verify_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.company_employer_verify
(
    id integer NOT NULL,
    employer_id integer NOT NULL,
    system_employee_id integer NOT NULL,
    email_verify boolean NOT NULL,
    verify_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_title
(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.system_employee
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_seeker
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.company_employer
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_employee_roles
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.system_employee (user_id)
    NOT VALID;


ALTER TABLE public.job_seeker_verify
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seeker (user_id)
    NOT VALID;


ALTER TABLE public.company_employer_verify
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.company_employer (user_id)
    NOT VALID;


ALTER TABLE public.company_employer_verify
    ADD FOREIGN KEY (system_employee_id)
    REFERENCES public.system_employee (user_id)
    NOT VALID;

END;